import { NextResponse } from 'next/server';

export const maxDuration = 60; // 60s timeout for Vercel functions

/**
 * POST /api/floorplan-text-mastermind
 * Body: { step3ImageUrl: string, roomSchedule: any }
 * Computes text correction prompt via Gemini 1.5 Pro on OpenRouter to fix typos/duplicates.
 */
export async function POST(req: Request) {
  try {
    const { step3ImageUrl, roomSchedule } = await req.json();

    if (!step3ImageUrl || !roomSchedule) {
      return NextResponse.json({ error: 'Missing step3ImageUrl or roomSchedule' }, { status: 400 });
    }

    const openRouterKey = process.env.OPENROUTER_API_KEY;
    if (!openRouterKey) {
      throw new Error("Missing OPENROUTER_API_KEY in environment variables");
    }

    console.log('[Text Mastermind] Initializing text correction via OpenRouter...');

    const prompt = `You are a master mathematical architect and a strict QA text proofreader for an AI image generator.
The attached image is the final CAD floor plan generated by a previous AI step.
Due to heavy squashing, the previous AI may have corrupted the text labels (e.g. turning "FLAT B" into "BLAT B", or "TOILET" into "TOAET").
It may also have hallucinated duplicate rooms (e.g. drawing two "KITCHEN A"s instead of a Bedroom) because it couldn't read the text.

### The ONLY correct room list:
${JSON.stringify(roomSchedule, null, 2)}

### Your Task:
1. Examine the image carefully. Read every single text label inside the rooms.
2. Compare the text labels in the image against the JSON schedule above.
3. Identify exactly which text labels in the image are misspelled or typoed.
4. Identify if any rooms were duplicated (e.g. two Kitchens in Flat A) or if any hallucinated rooms were added (e.g. "STUDY", "STORE", "UTILITY").
5. Write a short, highly specific prompt for the final AI image editor (Grok) to fix these exact errors.
6. Tell the AI exactly what to replace. For example: "In the middle right block, replace the text 'BLAT B' with 'FLAT B'. Change the text 'TOAET' to 'TOILET'. Rename the second 'KITCHEN A' to 'BEDROOM 2 (FLAT A)'".
7. DO NOT ask the AI to change the structure of the walls. It must ONLY edit the text labels.
8. Return ONLY the raw text prompt, nothing else. Do not use markdown. Start directly with the instructions.`;

    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${openRouterKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "openai/gpt-4o",
        messages: [
          {
            role: "user",
            content: [
              { type: "text", text: prompt },
              { type: "image_url", image_url: { url: step3ImageUrl } }
            ]
          }
        ]
      })
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error("[Text Mastermind] OpenRouter API Error:", errText);
      throw new Error(`OpenRouter API responded with status ${res.status}`);
    }

    const data = await res.json();
    const mastermindPrompt = data.choices[0]?.message?.content || "";
    
    console.log('[Text Mastermind] Successfully generated correction prompt.');

    return NextResponse.json({ prompt: mastermindPrompt });
  } catch (err: any) {
    console.error('[Text Mastermind] Error:', err.message || err);
    return NextResponse.json({ error: err.message || 'Text Mastermind calculation failed' }, { status: 500 });
  }
}
